import 'package:banking/data/contants.dart';
import 'package:banking/extensions/string_extensions.dart';
import 'package:banking/pages/input/input_item_widget.dart';
import 'package:banking/models/bank_model.dart';
import 'package:banking/pages/show_qr/show_qr_screen.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

class InputScreen extends StatefulWidget {
  const InputScreen({super.key});

  @override
  State<InputScreen> createState() => _InputScreenState();
}

class _InputScreenState extends State<InputScreen> {
  List<BankModel> _banks = [];
  List<BankModel> _allBanks = [];
  int _selectedIndex = -1;
  final TextEditingController _bankNumberController = TextEditingController();
  final TextEditingController _filterController = TextEditingController();
  bool _isLoading = false;
  String filter = '';
  String _bankNumber = '';

  bool get _isValidateCreateCode =>
      _selectedIndex != -1 && _bankNumber.isNotNullOrEmpty;

  @override
  void initState() {
    super.initState();
    getBanks();
    _registerListener();
  }

  void _registerListener() {
    _bankNumberController.addListener(() {
      setState(() {
        _bankNumber = _bankNumberController.text;
      });
    });
    _filterController.addListener(() {
      filter = _filterController.text;
      setState(() {
        _banks = _allBanks
            .where(
              (bank) =>
                  (bank.name?.toLowerCase().contains(filter.toLowerCase()) ??
                      false) ||
                  (bank.shortName
                          ?.toLowerCase()
                          .contains(filter.toLowerCase()) ??
                      false) ||
                  (bank.code?.toLowerCase().contains(filter.toLowerCase()) ??
                      false),
            )
            .toList();
      });
    });
  }

  Future<void> getBanks() async {
    setState(() {
      _isLoading = true;
    });
    final response = await Dio().get(AppConstants.banks);
    setState(() {
      _allBanks = Autogenerated.fromJson(response.data).data ?? [];
      _banks = _allBanks;
      _isLoading = false;
    });
  }

  void _onCreateQRCode(BuildContext cContext) {
    if (!_isValidateCreateCode) {
      return;
    }
    if (_bankNumberController.text.isNotEmpty && _selectedIndex != -1) {
      Navigator.push(
        cContext,
        MaterialPageRoute(
          builder: (context) => ShowQRScreen(
            qrCode:
                'https://img.vietqr.io/image/${_banks[_selectedIndex].shortName}-${_bankNumberController.text}-compact.png?amount=%3CAMOUNT%3E&addInfo=%3CDESCRIPTION%3E&accountName=%3CACCOUNT_NAME%3E',
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Tạo QR Chuyển khoản"),
        actions: [
          IconButton(
              onPressed: () {
                showDialog(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: const Text('Chức năng đang phát triển'),
                    content: const Text(
                      'Chức năng lưu lại lịch sử tài khoản ngân hàng sẽ được phát triển trong thời gian tới do nhà phát triển chưa đủ kinh phí duy trì!',
                    ),
                    actions: [
                      TextButton(
                          onPressed: () {
                            Navigator.pop(context);
                          },
                          child: const Text('Ok'))
                    ],
                  ),
                );
              },
              icon: const Icon(
                Icons.history_outlined,
                size: 24,
              ))
        ],
      ),
      body: Builder(
        builder: (context) => _isLoading
            ? const Center(child: CircularProgressIndicator())
            : Column(
                children: [
                  Container(
                    margin: const EdgeInsets.all(16),
                    child: TextField(
                      decoration: const InputDecoration(
                        labelText: 'Số tài khoản ngân hàng',
                        hintText: '1912312312',
                        border: OutlineInputBorder(),
                      ),
                      style: const TextStyle(
                        fontSize: 16,
                      ),
                      controller: _bankNumberController,
                    ),
                  ),
                  Container(
                    margin: const EdgeInsets.all(16),
                    child: TextField(
                      controller: _filterController,
                      decoration: const InputDecoration(
                        labelText: 'Tìm kiếm ngân hàng',
                        hintText: 'Techcombank',
                        border: OutlineInputBorder(),
                        suffixIcon: Icon(Icons.search),
                      ),
                      style: const TextStyle(
                        fontSize: 16,
                      ),
                    ),
                  ),
                  Expanded(
                    child: ListView.separated(
                      itemBuilder: (context, index) => InputItemWidget(
                          isSelected: index == _selectedIndex,
                          bank: _banks[index],
                          onTap: () {
                            setState(() {
                              _selectedIndex = index;
                            });
                          }),
                      separatorBuilder: (context, index) => const Divider(
                        height: 5,
                        color: Colors.transparent,
                      ),
                      itemCount: _banks.length,
                    ),
                  ),
                  InkWell(
                    onTap: () => _onCreateQRCode(context),
                    child: Container(
                      margin: const EdgeInsets.only(
                        left: 20,
                        right: 20,
                        bottom: 24,
                        top: 8,
                      ),
                      width: double.infinity,
                      padding: const EdgeInsets.symmetric(
                        vertical: 16,
                      ),
                      decoration: BoxDecoration(
                          color: _isValidateCreateCode
                              ? Colors.deepPurple
                              : Colors.grey,
                          borderRadius: BorderRadius.circular(
                            12,
                          )),
                      alignment: Alignment.center,
                      child: const Text(
                        'Tạo QR Code',
                        style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                          fontSize: 18,
                        ),
                      ),
                    ),
                  )
                ],
              ),
      ),
    );
  }
}
