class Autogenerated {
  String? code;
  String? desc;
  List<BankModel>? data;

  Autogenerated({this.code, this.desc, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    desc = json['desc'];
    if (json['data'] != null) {
      data = <BankModel>[];
      json['data'].forEach((v) {
        data!.add(BankModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['code'] = code;
    data['desc'] = desc;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class BankModel {
  int? id;
  String? name;
  String? code;
  String? bin;
  String? shortName;
  String? logo;
  int? transferSupported;
  int? lookupSupported;
  int? support;
  int? isTransfer;
  String? swiftCode;

  BankModel(
      {this.id,
      this.name,
      this.code,
      this.bin,
      this.shortName,
      this.logo,
      this.transferSupported,
      this.lookupSupported,
      this.support,
      this.isTransfer,
      this.swiftCode});

  BankModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    code = json['code'];
    bin = json['bin'];
    shortName = json['shortName'];
    logo = json['logo'];
    transferSupported = json['transferSupported'];
    lookupSupported = json['lookupSupported'];
    shortName = json['short_name'];
    support = json['support'];
    isTransfer = json['isTransfer'];
    swiftCode = json['swift_code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    data['bin'] = bin;
    data['shortName'] = shortName;
    data['logo'] = logo;
    data['transferSupported'] = transferSupported;
    data['lookupSupported'] = lookupSupported;
    data['support'] = support;
    data['isTransfer'] = isTransfer;
    data['swift_code'] = swiftCode;
    return data;
  }
}
